/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('@arco-design/web-vue')['Button']
    AConfigProvider: typeof import('@arco-design/web-vue')['ConfigProvider']
    ADatePicker: typeof import('@arco-design/web-vue')['DatePicker']
    ARow: typeof import('@arco-design/web-vue')['Row']
    ASpace: typeof import('@arco-design/web-vue')['Space']
    CalendarView: typeof import('./src/components/CalendarView.vue')['default']
    DatePickerPanel: typeof import('./src/components/DatePickerPanel.vue')['default']
    SlashDatePicker: typeof import('./src/components/SlashDatePicker.vue')['default']
  }
}
